#!/usr/bin/env bash

usage="

    -h show this help text
    -a artifact ID
    -n application name
    -t packaging type (jar or war)
    -r location of maven module / parent repo

    Examples:

    -- Add docker config with packaging type jar:

    ./eid-application-template/add-docker-config -t jar -a serviceprovider-admin -g no.difi -n serviceprovider-admin

    -- Add docker config to a module in an existing repo:

    ./eid-application-template/add-docker-config -t war -a serviceprovider-admin -g no.difi -n serviceprovider-admin -r eid-serviceprovider-admin
"


while getopts "l:" opt; do
  case ${opt} in
     l )
      location=$OPTARG
      ;;
    \? ) echo "Usage: cmd [-a <artifactId>] [-g <groupId>] [-n <name>]"
         exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if [ ! -d "$location/docker" ]; then
  echo "Couldn't find required docker folder in dir $location, aborting"
  exit 1
fi

if [ ! -f app_info ]; then
  cp templates/app_info .
fi

. app_info

app_dir=$location

mkdir ${app_dir}docker/$app_name
cp -r templates/docker/placeholder-app-name/* ${app_dir}docker/$app_name
mkdir -p ${app_dir}docker/$app_name/$packaging


find ${app_dir}docker/$app_name -type f -exec sed -i -e "s/placeholder-app-name/$app_name/g" {} \; -exec sed -i -e "s/placeholder_puppet_module/$puppet_module_name/g" {} \; -exec sed -i -e "s/placeholder-artifact-name/$artifact_id/g" {} \; -exec sed -i -e "s/placeholder-group-id/$group_id/g" {} \; -exec sed -i -e "s/placeholder-packaging/$packaging/g" {} \;

