#!/usr/bin/env bash

while getopts "a:n:r:t:" opt; do
  case ${opt} in
    a )
      artifactId=$OPTARG
      ;;
    n )
      app_name=$OPTARG
      ;;
    r )
      repo_dir=$OPTARG
      ;;
    t )
      packaging=$OPTARG
      ;;
    \? ) echo "Usage: cmd [-a <artifactId>] [-g <groupId>] [-n <name>]"
         exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if [ ! -z $repo_dir ]; then
  app_dir="$repo_dir"
else
  app_dir="$app_name"
fi

cp -r eid-application-template/templates/docker/placeholder-app-name/* $app_dir/docker/$app_name
mkdir -p $app_dir/docker/$app_name/$packaging


find $app_dir/docker/$app_name -type f -exec sed -i -e "s/placeholder-app-name/$app_name/g" {} \; -exec sed -i -e "s/placeholder_puppet_module/$puppet_module_name/g" {} \; -exec sed -i -e "s/placeholder-artifact-name/$artifactId/g" {} \; -exec sed -i -e "s/placeholder-group-id/$groupId/g" {} \; -exec sed -i -e "s/placeholder-packaging/$packaging/g" {} \;

